{
 "title": "Redis Plane Tracker",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "API Calls",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "command": "hget",
     "field": "${__from:date:YYYYMMDD}",
     "keyName": "stats:flightawareapicalls",
     "streamingDataType": "DataFrame",
     "type": "command"
    }
   ]
  },
  {
   "title": "API Costs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "command": "hget",
     "field": "${__from:date:YYYYMMDD}",
     "keyName": "stats:flightawareapicalls",
     "streamingDataType": "DataFrame",
     "type": "command"
    }
   ]
  },
  {
   "title": "Messages Decoded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "command": "hget",
     "field": "${__from:date:YYYYMMDD}",
     "keyName": "stats:messagecounts",
     "streamingDataType": "DataFrame",
     "type": "command"
    }
   ]
  },
  {
   "title": "Aircraft Tracked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "ZCARD stats:planesseen", "streamingDataType": "DataFrame", "type": "cli" }
   ]
  },
  {
   "title": "Aircraft Types",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "ZCARD stats:aircrafttypes", "streamingDataType": "DataFrame", "type": "cli" }
   ]
  },
  {
   "title": "Operators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "ZCARD stats:operators", "streamingDataType": "DataFrame", "streamingInterval": 2000, "type": "cli" }
   ]
  },
  {
   "title": "Most Seen Widebody",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "panelId": 10 }
   ]
  },
  {
   "title": "Most Seen Narrowbody",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "747s Seen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "command": "zrange",
     "keyName": "stats:aircrafttypes",
     "max": "-1",
     "min": "0",
     "streamingDataType": "DataFrame",
     "streamingInterval": 2000,
     "type": "command"
    }
   ]
  },
  {
   "title": "A380s Seen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "command": "zrange",
     "keyName": "stats:aircrafttypes",
     "max": "-1",
     "min": "0",
     "streamingDataType": "DataFrame",
     "streamingInterval": 2000,
     "type": "command"
    }
   ]
  },
  {
   "title": "A340s Seen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "command": "zrange",
     "keyName": "stats:aircrafttypes",
     "max": "-1",
     "min": "0",
     "streamingDataType": "DataFrame",
     "streamingInterval": 2000,
     "type": "command"
    }
   ]
  },
  {
   "title": "757s Seen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "command": "zrange",
     "keyName": "stats:aircrafttypes",
     "max": "-1",
     "min": "0",
     "streamingDataType": "DataFrame",
     "streamingInterval": 2000,
     "type": "command"
    }
   ]
  },
  {
   "title": "Most Popular Origin",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "keyName": "stats:origins",
     "max": "-1",
     "min": "-1",
     "query": "zrange stats:origins -1 -1",
     "streamingDataType": "DataFrame",
     "streamingInterval": 2000,
     "type": "cli"
    }
   ]
  },
  {
   "title": "Most Popular Destination",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "keyName": "stats:origins",
     "max": "-1",
     "min": "-1",
     "query": "zrange stats:destinations -1 -1",
     "streamingDataType": "DataFrame",
     "streamingInterval": 2000,
     "type": "cli"
    }
   ]
  },
  {
   "title": "Most Popular Route",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "keyName": "stats:origins",
     "max": "-1",
     "min": "-1",
     "query": "zrange stats:routes -1 -1",
     "streamingDataType": "DataFrame",
     "streamingInterval": 2000,
     "type": "cli"
    }
   ]
  },
  {
   "title": "Rarest Seen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "command": "zrange",
     "keyName": "stats:aircrafttypes",
     "max": "0",
     "min": "0",
     "type": "command"
    }
   ]
  },
  {
   "title": "Top 10 Most Seen Aircraft",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "command": "zrange",
     "keyName": "stats:planesseen",
     "max": "-1",
     "min": "0",
     "streamingDataType": "DataFrame",
     "streamingInterval": 2000,
     "type": "command"
    }
   ]
  },
  {
   "title": "Most Recently Seen",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "ft.aggregate idx:flights * load 6 @operator_name @flight_number @origin_iata @destination_iata @aircraft_type @last_updated filter exists(@aircraft_type) sortby 2 @last_updated desc limit 0 1",
     "streamingDataType": "DataFrame",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Top 15 Operators",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "command": "zrange",
     "keyName": "stats:operators",
     "max": "-1",
     "min": "0",
     "streamingDataType": "DataFrame",
     "streamingInterval": 2000,
     "type": "command"
    }
   ]
  },
  {
   "title": "Top 5 Routes",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "command": "zrange",
     "keyName": "stats:routes",
     "max": "-1",
     "min": "0",
     "streamingDataType": "DataFrame",
     "streamingInterval": 2000,
     "type": "command"
    }
   ]
  },
  {
   "title": "Top 20 Aircraft Types",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "command": "zrange",
     "keyName": "stats:aircrafttypes",
     "max": "-1",
     "min": "0",
     "streamingDataType": "DataFrame",
     "streamingInterval": 2000,
     "type": "command"
    }
   ]
  },
  {
   "title": "Top 15 Widebodies",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 23 },
   "targets": [
    {
     "command": "zrange",
     "keyName": "stats:aircrafttypes",
     "max": "-1",
     "min": "0",
     "streamingDataType": "DataFrame",
     "streamingInterval": 2000,
     "type": "command"
    }
   ]
  },
  {
   "title": "Top 15 Origins",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 7, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "command": "zrange",
     "keyName": "stats:origins",
     "max": "-1",
     "min": "0",
     "streamingDataType": "DataFrame",
     "streamingInterval": 2000,
     "type": "command"
    }
   ]
  },
  {
   "title": "Top 15 Destinations",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 7, "x": 7, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "command": "zrange",
     "keyName": "stats:destinations",
     "max": "-1",
     "min": "0",
     "streamingDataType": "DataFrame",
     "streamingInterval": 2000,
     "type": "command"
    }
   ]
  },
  {
   "title": "Top 15 Narrowbodies",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 32 },
   "targets": [
    {
     "command": "zrange",
     "keyName": "stats:aircrafttypes",
     "max": "-1",
     "min": "0",
     "streamingDataType": "DataFrame",
     "streamingInterval": 2000,
     "type": "command"
    }
   ]
  }
 ]
}